// Code generated by protoc-gen-go. DO NOT EDIT.
// source: state.proto

/*
Package erc20_pb is a generated protocol buffer package.

It is generated from these files:
	state.proto
	payload.proto

It has these top-level messages:
	State
	Payload
	AnyData
	TransferPayload
	ApprovePayload
	TransferFromPayload
	InitTokenStatePayload
*/
package erc20_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State struct {
}

func (m *State) Reset()                    { *m = State{} }
func (m *State) String() string            { return proto.CompactTextString(m) }
func (*State) ProtoMessage()               {}
func (*State) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type State_Balances struct {
	Balances map[string]string `protobuf:"bytes,1,rep,name=balances" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *State_Balances) Reset()                    { *m = State_Balances{} }
func (m *State_Balances) String() string            { return proto.CompactTextString(m) }
func (*State_Balances) ProtoMessage()               {}
func (*State_Balances) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *State_Balances) GetBalances() map[string]string {
	if m != nil {
		return m.Balances
	}
	return nil
}

type State_Allowed struct {
	Allowed map[string]string `protobuf:"bytes,1,rep,name=allowed" json:"allowed,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *State_Allowed) Reset()                    { *m = State_Allowed{} }
func (m *State_Allowed) String() string            { return proto.CompactTextString(m) }
func (*State_Allowed) ProtoMessage()               {}
func (*State_Allowed) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *State_Allowed) GetAllowed() map[string]string {
	if m != nil {
		return m.Allowed
	}
	return nil
}

func init() {
	proto.RegisterType((*State)(nil), "erc20_pb.State")
	proto.RegisterType((*State_Balances)(nil), "erc20_pb.State.Balances")
	proto.RegisterType((*State_Allowed)(nil), "erc20_pb.State.Allowed")
}

func init() { proto.RegisterFile("state.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2e, 0x49, 0x2c,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x2d, 0x4a, 0x36, 0x32, 0x88, 0x2f,
	0x48, 0x52, 0x9a, 0xcb, 0xc4, 0xc5, 0x1a, 0x0c, 0x92, 0x91, 0xea, 0x66, 0xe4, 0xe2, 0x70, 0x4a,
	0xcc, 0x49, 0xcc, 0x4b, 0x4e, 0x2d, 0x16, 0x72, 0xe2, 0xe2, 0x48, 0x82, 0xb2, 0x25, 0x18, 0x15,
	0x98, 0x35, 0xb8, 0x8d, 0xd4, 0xf4, 0x60, 0x7a, 0xf4, 0xc0, 0xea, 0xf5, 0x60, 0x6a, 0xe1, 0x0c,
	0xd7, 0xbc, 0x92, 0xa2, 0xca, 0x20, 0xb8, 0x3e, 0x29, 0x6b, 0x2e, 0x5e, 0x14, 0x29, 0x21, 0x01,
	0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x48, 0x84,
	0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x09, 0x2c, 0x06, 0xe1, 0x58, 0x31, 0x59, 0x30,
	0x4a, 0xb5, 0x32, 0x72, 0xb1, 0x3b, 0xe6, 0xe4, 0xe4, 0x97, 0xa7, 0xa6, 0x08, 0xd9, 0x71, 0xb1,
	0x27, 0x42, 0x98, 0x50, 0xb7, 0xa8, 0xa0, 0xbb, 0x05, 0xaa, 0x12, 0x46, 0x43, 0x5c, 0x02, 0xd3,
	0x24, 0x65, 0xc5, 0xc5, 0x83, 0x2c, 0x41, 0x8a, 0x3b, 0x92, 0xd8, 0xc0, 0x01, 0x66, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xd6, 0x56, 0xe4, 0xf7, 0x3f, 0x01, 0x00, 0x00,
}
